workflows:
ios:
name: iOS Build
triggering:
events:
- push
branch_patterns:
- pattern: main
instance_type: mac_mini_m1
max_build_duration: 60
integrations:
app_store_connect: your_apple_id # Replace with your Apple email
environment:
flutter: stable
scripts:
- name: Install pods
script: |
cd ios
pod install
- name: Build IPA
script: |
flutter build ipa --release
artifacts:
- build/ios/ipa/*.ipa
publishing:
email:
recipients:
- a247xxx@gmail.com # Optional: email IPA to yourself