workflows:
  ios:
    name: iOS Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS (No Signing)
        script: |
          # This creates a .app bundle, not a final .ipa
          flutter build ios --release --no-codesign
      - name: Package Unsigned IPA (Workaround)
        script: |
          # Manually creating the IPA structure so it can be exported as an artifact
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r unsigned_app.ipa Payload
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - a247xxx@gmail.com
