workflows:
  ios-build:
    name: iOS Unsigned Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Get Flutter dependencies
        script: |
          # This generates the Generated.xcconfig file required by your Podfile
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS (No Signing)
        script: |
          # Build the .app bundle without requiring Apple certificates
          flutter build ios --release --no-codesign
      - name: Create Unsigned IPA
        script: |
          # Manual packaging into an IPA so you can download it as an artifact
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r unsigned_release.ipa Payload
    artifacts:
      - "*.ipa"
    publishing:
      email:
        recipients:
          - a247xxx@gmail.com
