workflows:
  ios-unsigned-workflow:
    name: iOS Unsigned Direct Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Set up Flutter dependencies
        script: | 
          flutter clean
          flutter pub get
      - name: Install CocoaPods
        script: | 
          cd ios && pod install --repo-update
      - name: Build Flutter AOT
        script: | 
          # This prepares the Dart code and assets without touching Xcode signing logic
          flutter build ios --release --no-codesign
      - name: Direct Xcode Compilation
        script: | 
          # We use -allowProvisioningDeviceRegistration as a dummy flag 
          # to keep the engine happy while forcing no signing.
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            COMPILER_INDEX_STORE_ENABLE=NO
      - name: Package Unsigned IPA
        script: | 
          # Create the Payload folder and move the app into it
          mkdir -p Payload
          # Search for the app in the build directory to ensure we grab the right one
          APP_PATH=$(find build/ios/iphoneos -name "*.app" | head -n 1)
          cp -r "$APP_PATH" Payload/
          zip -r dShift_unsigned.ipa Payload
    artifacts:
      - "*.ipa"
    publishing:
      email:
        recipients:
          - a247xxx@gmail.com
