workflows:
  ios-unsigned-workflow:
    name: iOS Unsigned Direct Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Set up Flutter dependencies
        script: | 
          flutter clean
          flutter pub get
      - name: Install CocoaPods
        script: | 
          cd ios && pod install --repo-update
      - name: Build iOS (Direct Xcode Bypass)
        script: | 
          # 1. Prepare the Flutter environment
          flutter build ios --release --no-codesign
          
          # 2. Force compile using xcodebuild to skip Flutter's "Team ID" check
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES
      - name: Package Unsigned IPA
        script: | 
          # Manually wrap the build into an IPA structure
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r dShift_unsigned.ipa Payload
    artifacts:
      - "*.ipa"
    publishing:
      email:
        recipients:
          - a247xxx@gmail.com
