workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS (No Codesign)
        script: |
          # The --no-codesign flag bypasses the "Development Team" requirement
          flutter build ios --release --no-codesign
      - name: Package Unsigned IPA
        script: |
          # Xcode creates a .app folder; we must wrap it in a 'Payload' folder to make an .ipa
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r dShift_unsigned.ipa Payload
    artifacts:
      - "*.ipa"
    publishing:
      email:
        recipients:
          - a247xxx@gmail.com
