workflows:
  ios:
    name: iOS Build
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: your_apple_id # Replace with your Apple email
    environment:
      flutter: stable
      xcode: latest # It's good practice to specify Xcode version
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
      - name: Build IPA
        script: |
          # Use --no-codesign if you handle signing later, 
          # or ensure your distribution certificates are set up in environment
          flutter build ipa --release --export-method=ad-hoc 
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - a247xxx@gmail.com
